
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Adj_D
{

    public Nullable<int> RID { get; set; }

    public Nullable<int> IID { get; set; }

    public string BNID { get; set; }

    public string ExpDT { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<double> Qty2 { get; set; }

    public Nullable<double> PurPrice { get; set; }

    public Nullable<double> Debit { get; set; }

    public Nullable<double> Credit { get; set; }

    public Nullable<double> SRT { get; set; }

    public Nullable<double> RCancel { get; set; }

    public int Adj_id { get; set; }

}

}
