
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Article
{

    public int ProductID { get; set; }

    public Nullable<int> ArticleTypeID { get; set; }

    public Nullable<int> StyleID { get; set; }

    public Nullable<int> BrandID { get; set; }

    public string ProductName { get; set; }

    public string ProductImage { get; set; }

    public string ArticleNo { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<int> BranchID { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string ModifyBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> CompanyID { get; set; }

}

}
