
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class COA_M
{

    public int CAC_Code { get; set; }

    public Nullable<double> MAC_Code { get; set; }

    public string MTitle { get; set; }

    public Nullable<double> SubAC_Code { get; set; }

    public string SubTitle { get; set; }

    public string CATitle { get; set; }

}

}
