
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Colors
{

    public int ColorID { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public Nullable<int> BranchID { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> IID { get; set; }

    public Nullable<int> CompanyID { get; set; }

}

}
