
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class EV_D
{

    public int RID { get; set; }

    public string Narr { get; set; }

    public string MOP_ID { get; set; }

    public string AC_Code { get; set; }

    public string InvNo { get; set; }

    public string ChkNo { get; set; }

    public string SlipNo { get; set; }

    public string Amt { get; set; }

    public string SRT { get; set; }

    public string RCancel { get; set; }

    public Nullable<int> ID { get; set; }

}

}
