
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class GL
{

    public Nullable<int> SRT { get; set; }

    public Nullable<int> RID { get; set; }

    public Nullable<int> RID2 { get; set; }

    public Nullable<int> TypeCode { get; set; }

    public Nullable<System.DateTime> GLDate { get; set; }

    public Nullable<System.DateTime> DueDT { get; set; }

    public Nullable<int> CompID { get; set; }

    public Nullable<int> SID { get; set; }

    public Nullable<int> AC_Code { get; set; }

    public Nullable<int> AC_Code2 { get; set; }

    public string Narration { get; set; }

    public string Rem { get; set; }

    public Nullable<int> MOP_ID { get; set; }

    public Nullable<int> ChkNo { get; set; }

    public Nullable<int> SlipNo { get; set; }

    public Nullable<double> Qty_IN { get; set; }

    public Nullable<double> Qty_Out { get; set; }

    public Nullable<double> IPrice { get; set; }

    public Nullable<double> PAmt { get; set; }

    public Nullable<double> DisP { get; set; }

    public Nullable<double> DisAmt { get; set; }

    public Nullable<double> DisRs { get; set; }

    public Nullable<double> Debit { get; set; }

    public Nullable<double> Credit { get; set; }

    public string VehNo { get; set; }

    public Nullable<int> Post_User_ID { get; set; }

    public Nullable<System.DateTime> Post_Date { get; set; }

    public int GL_id { get; set; }

}

}
