
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Itemledger
{

    public Nullable<int> SRT { get; set; }

    public Nullable<int> TypeCode { get; set; }

    public Nullable<int> RID { get; set; }

    public Nullable<System.DateTime> EDate { get; set; }

    public Nullable<int> AC_CODE { get; set; }

    public Nullable<int> WID { get; set; }

    public Nullable<int> SID { get; set; }

    public Nullable<int> IID { get; set; }

    public Nullable<int> BNID { get; set; }

    public Nullable<System.DateTime> ExpDT { get; set; }

    public Nullable<double> CTN { get; set; }

    public Nullable<double> PCS { get; set; }

    public Nullable<double> OPN { get; set; }

    public Nullable<double> PJ { get; set; }

    public Nullable<double> PRJ { get; set; }

    public Nullable<double> SJ { get; set; }

    public Nullable<double> SRJ { get; set; }

    public Nullable<double> SCH_IN { get; set; }

    public Nullable<double> SCH_Out { get; set; }

    public Nullable<double> SCH_Out2 { get; set; }

    public Nullable<double> ADJ_IN { get; set; }

    public Nullable<double> ADJ_OUT { get; set; }

    public Nullable<double> TR_IN { get; set; }

    public Nullable<double> TR_OUT { get; set; }

    public Nullable<double> MFG_IN { get; set; }

    public Nullable<double> MFG_OUT { get; set; }

    public Nullable<double> PurPrice { get; set; }

    public Nullable<double> SalesPriceP { get; set; }

    public Nullable<double> AddPer { get; set; }

    public Nullable<double> AddAmt { get; set; }

    public Nullable<double> SalesPrice { get; set; }

    public Nullable<double> PAmt { get; set; }

    public Nullable<double> DisP { get; set; }

    public Nullable<double> DisAmt { get; set; }

    public Nullable<double> DisRs { get; set; }

    public Nullable<double> Amt { get; set; }

    public Nullable<double> Amt2 { get; set; }

    public Nullable<double> RCancel { get; set; }

    public int LegderId { get; set; }

    public Nullable<int> CompanyID { get; set; }

}

}
