
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Items_Cat
{

    public int CatID { get; set; }

    public string Cat { get; set; }

    public Nullable<bool> isDeleted { get; set; }

    public Nullable<int> CompanyID { get; set; }

    public string img { get; set; }

    public string Images { get; set; }

}

}
