
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Item_Maker
{

    public int MakerId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public Nullable<int> CompanyID { get; set; }

    public Nullable<bool> IsDelete { get; set; }

}

}
