
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class IUnit
{

    public int unit_id { get; set; }

    public string IUnit1 { get; set; }

    public Nullable<bool> active { get; set; }

    public string crtBy { get; set; }

    public Nullable<System.DateTime> crtDate { get; set; }

    public string modBy { get; set; }

    public string modDate { get; set; }

    public Nullable<int> CompanyID { get; set; }

    public string IUnit11 { get; set; }

    public string IUnit111 { get; set; }

}

}
