
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class JV_M
{

    public int RID { get; set; }

    public Nullable<double> CompID { get; set; }

    public Nullable<System.DateTime> EDate { get; set; }

    public Nullable<double> SID { get; set; }

    public string Rem { get; set; }

    public Nullable<double> APost { get; set; }

    public Nullable<double> Posted { get; set; }

    public Nullable<double> RCancel { get; set; }

    public string Create_User_ID { get; set; }

    public string Create_Date { get; set; }

    public string Edit_User_ID { get; set; }

    public string Edit_Date { get; set; }

    public string Del_User_ID { get; set; }

    public string Del_Date { get; set; }

}

}
