
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Party_Type
{

    public int PType_ID { get; set; }

    public string Party_Type1 { get; set; }

    public Nullable<bool> isDeleted { get; set; }

    public Nullable<int> CompanyID { get; set; }

    public string Party_Type11 { get; set; }

    public string Party_Type111 { get; set; }

}

}
