
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class PO_D
{

    public string RID { get; set; }

    public string IID { get; set; }

    public string CTN { get; set; }

    public string PCS { get; set; }

    public string SCH { get; set; }

    public string Qty { get; set; }

    public string PurPrice { get; set; }

    public string PAmt { get; set; }

    public string DisP { get; set; }

    public string DisAmt { get; set; }

    public string DisRs { get; set; }

    public string Amt { get; set; }

    public string SRT { get; set; }

    public string RCancel { get; set; }

    public int Pur_D_ID { get; set; }

    public Nullable<int> UnitId { get; set; }

}

}
