
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Pur_D
{

    public Nullable<double> RID { get; set; }

    public Nullable<double> IID { get; set; }

    public Nullable<double> BNID { get; set; }

    public Nullable<System.DateTime> ExpDT { get; set; }

    public Nullable<double> CTN { get; set; }

    public Nullable<double> PCS { get; set; }

    public string SCH { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<double> PurPrice { get; set; }

    public Nullable<double> PAmt { get; set; }

    public Nullable<double> DisP { get; set; }

    public Nullable<double> DisAmt { get; set; }

    public Nullable<double> DisRs { get; set; }

    public Nullable<double> Amt { get; set; }

    public Nullable<double> SRT { get; set; }

    public Nullable<double> RCancel { get; set; }

    public int Pur_D_ID { get; set; }

    public Nullable<int> Pur_D_UnitID { get; set; }

    public Nullable<double> SAmt { get; set; }

    public Nullable<double> SRate { get; set; }

}

}
