
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class PurR_M
{

    public int RID { get; set; }

    public Nullable<double> CompID { get; set; }

    public Nullable<System.DateTime> EDate { get; set; }

    public Nullable<double> AC_Code { get; set; }

    public string RID2 { get; set; }

    public string InvDT { get; set; }

    public string BiltyNo { get; set; }

    public Nullable<double> SID { get; set; }

    public Nullable<double> WID { get; set; }

    public Nullable<double> NetAmt { get; set; }

    public string Rem { get; set; }

    public Nullable<double> APost { get; set; }

    public Nullable<double> Posted { get; set; }

    public Nullable<double> RCancel { get; set; }

    public Nullable<double> Create_User_ID { get; set; }

    public Nullable<System.DateTime> Create_Date { get; set; }

    public Nullable<double> Edit_User_ID { get; set; }

    public Nullable<System.DateTime> Edit_Date { get; set; }

    public string Del_User_ID { get; set; }

    public string Del_Date { get; set; }

    public string invRNo { get; set; }

    public string invNo { get; set; }

}

}
