
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class PV_M
{

    public int RID { get; set; }

    public Nullable<int> CompID { get; set; }

    public Nullable<System.DateTime> EDate { get; set; }

    public Nullable<int> AC_Code { get; set; }

    public Nullable<int> SID { get; set; }

    public string Rem { get; set; }

    public Nullable<int> APost { get; set; }

    public Nullable<int> Posted { get; set; }

    public Nullable<int> RCancel { get; set; }

    public Nullable<int> Create_User_ID { get; set; }

    public Nullable<System.DateTime> Create_Date { get; set; }

    public Nullable<int> Edit_User_ID { get; set; }

    public Nullable<System.DateTime> Edit_Date { get; set; }

    public Nullable<int> Del_User_ID { get; set; }

    public Nullable<System.DateTime> Del_Date { get; set; }

    public Nullable<bool> isDeleted { get; set; }

}

}
