
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class RV_D
{

    public Nullable<int> RID { get; set; }

    public string Narr { get; set; }

    public Nullable<int> MOP_ID { get; set; }

    public string AC_Code { get; set; }

    public Nullable<int> InvNo { get; set; }

    public Nullable<int> ChkNo { get; set; }

    public Nullable<int> SlipNo { get; set; }

    public Nullable<double> PreAmt { get; set; }

    public Nullable<double> Amt { get; set; }

    public Nullable<double> DisAmt { get; set; }

    public Nullable<double> BalAmt { get; set; }

    public Nullable<double> SRT { get; set; }

    public Nullable<double> RCancel { get; set; }

    public int ID { get; set; }

    public Nullable<System.DateTime> checkDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

}

}
