
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Sale_Pur_D_Sale
{

    public int Sale_ID { get; set; }

    public Nullable<int> RID { get; set; }

    public Nullable<int> CityID { get; set; }

    public Nullable<int> VillageID { get; set; }

    public Nullable<int> VendorID { get; set; }

    public Nullable<decimal> PukhtaBikri { get; set; }

    public Nullable<int> LongerTadat { get; set; }

    public Nullable<decimal> KhamBikri { get; set; }

    public Nullable<decimal> Phaliyan { get; set; }

    public Nullable<decimal> CustomerExpense { get; set; }

}

}
