
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Sale_Pur_M
{

    public int RId { get; set; }

    public string VehicalNo { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<decimal> Rent { get; set; }

    public Nullable<decimal> pashgi { get; set; }

    public Nullable<decimal> bharai_chatai_kata_kharacha { get; set; }

    public Nullable<decimal> Office_khata { get; set; }

    public Nullable<decimal> CarAmad_AmadKharcha { get; set; }

    public Nullable<decimal> gari_OfficeKharcha { get; set; }

    public Nullable<decimal> Total_Purchase { get; set; }

    public Nullable<decimal> advanceBuilty { get; set; }

    public Nullable<decimal> OwnBuilty { get; set; }

}

}
