
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Sale_Pur_D_Pur
{

    public int Pur_ID { get; set; }

    public Nullable<int> RID { get; set; }

    public Nullable<int> VendorID { get; set; }

    public Nullable<int> ItemID { get; set; }

    public Nullable<int> UnitID { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<decimal> Pur_Price { get; set; }

    public Nullable<decimal> Pur_Total { get; set; }

    public Nullable<decimal> Comm { get; set; }

    public Nullable<int> CvenID { get; set; }

    public Nullable<decimal> Total { get; set; }

}

}
