
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Sales_D
{

    public int SD_ID { get; set; }

    public Nullable<double> RID { get; set; }

    public Nullable<double> IID { get; set; }

    public Nullable<double> BNID { get; set; }

    public Nullable<System.DateTime> ExpDT { get; set; }

    public string CTN { get; set; }

    public Nullable<double> PCS { get; set; }

    public string SCH { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<double> PurPrice { get; set; }

    public Nullable<double> SalesPriceP { get; set; }

    public string AddPer { get; set; }

    public string AddAmt { get; set; }

    public Nullable<double> SalesPrice { get; set; }

    public Nullable<double> PAmt { get; set; }

    public string DisP { get; set; }

    public string DisAmt { get; set; }

    public string DisRs { get; set; }

    public Nullable<double> Amt2 { get; set; }

    public Nullable<double> Amt { get; set; }

    public Nullable<double> PCK_Det { get; set; }

    public Nullable<double> SRT { get; set; }

    public Nullable<double> RCancel { get; set; }

}

}
