
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_KOT
{

    public int Id { get; set; }

    public string KotNo { get; set; }

    public string OrderID { get; set; }

    public Nullable<bool> iscomplete { get; set; }

    public Nullable<int> CatID { get; set; }

}

}
