
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_Warehouse
{

    public int WID { get; set; }

    public string Warehouse { get; set; }

    public string WSht { get; set; }

    public Nullable<int> CompanyID { get; set; }

    public Nullable<bool> isDelete { get; set; }

    public string Address { get; set; }

    public string Telephone { get; set; }

    public string Email { get; set; }

}

}
