
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblStock
{

    public int ItemID { get; set; }

    public string BatchNO { get; set; }

    public Nullable<System.DateTime> Expiry { get; set; }

    public Nullable<int> Quantity { get; set; }

    public int Id { get; set; }

}

}
