
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lib.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Zone
{

    public int ZID { get; set; }

    public string Zone1 { get; set; }

    public Nullable<bool> is_Deleted { get; set; }

    public Nullable<int> CompanyID { get; set; }

    public string Zone11 { get; set; }

    public string Zone111 { get; set; }

}

}
